import os
ORIG_INPUT_DATASET = "Food-5K";
BASE_PATH = "dataset";
TRAIN = "training";
VAL = "validation"
TEST = "evaluation";

BASE_FEATURE_OUTPUT = "Features";
BASE_MODEL_PATH = "Models"

MAX_WIDTH = 224;
MAX_HEIGHT = 224;
NETWORK_SIZE =224;

IMAGE_FEATURE_DIM = 1280;
FEATURES_HIDDEN = 500;

LEARNING_RATE = 0.01;
EPOCHS = 2;


